// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injection

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/golang-crud/handler"
	"github.com/teten-nugraha/golang-crud/repository"
	"github.com/teten-nugraha/golang-crud/service"
)

// Injectors from wire.go:

func InitMahasiswaAPI(db *gorm.DB) handler.MahasiswaAPI {
	mahasiswaRepository := repository.ProviderMahasiswaRepository(db)
	mahasiswaService := service.ProviderMahasiswaService(mahasiswaRepository)
	mahasiswaAPI := handler.ProviderMahasiswaAPI(mahasiswaService)
	return mahasiswaAPI
}